import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    contentContainer: {
     flexGrow: 1,
      },
    image: {
      flex: 1,
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
    },
    imagePerson: {
      width: 120,
      height: 120,
      position: 'absolute',
      alignSelf: 'center',
      top: -85,
      backgroundColor: '#F6F6F6',
      borderRadius: 16,
    },
    text: {
        color: 'black',
        fontSize: 35,
        fontFamily: 'Roboto-Bold',
        lineHeight: 35,
        fontWeight: '500',
        textAlign: 'center',
        marginBottom:20,
        marginTop:Platform.OS === 'ios' ? 52 : 35,
      },
      overlay: {
        flex: 1,
        justifyContent: 'flex-end',
        marginTop:'55%',
      },
      overlayLogin: {
        flex: 1,
        justifyContent: 'flex-end',
        marginTop:Platform.OS === 'ios' ? "70%" : 35,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
      },
      registrationContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
        borderTopLeftRadius: 25,
        borderTopRightRadius:25,
      },
      inputContainer: {
        marginBottom: 16,
      },
      input: {
        width:343,
        height:50,
        backgroundColor:'#F6F6F6',
        paddingLeft:16,
        borderColor:'#E8E8E8',
        borderRadius:5,
        borderWidth:1,
        marginBottom:20,
        fontFamily:'Roboto',
        fontWeight:'400',
        fontSize:16,
        lineHeight:18,
      },
      passwordInput: {
        flex: 1,
        height: 50,
        backgroundColor: '#F6F6F6',
        paddingLeft: 16,
        borderColor: '#E8E8E8',
        borderRadius: 5,
        borderWidth: 1,
        marginBottom:20,
      },
    showPasswordButton: {
      position: 'absolute',
      right: 16,
      top: 16,
      zIndex: 1,
      },
      showPasswordButtonText: {
        color: 'blue',
        fontFamily:'Roboto',
        lineHeight:19,
        fontWeight:'400',
      },
      passwordInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
      },
      roundButton: {
        backgroundColor: '#FF6C00',
        borderRadius: 100,
        paddingVertical: 16,
        paddingHorizontal: 32,
        marginTop: 16,
        marginBottom:32,
      },
      buttonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '400',
        lineHeight:19,
        textAlign: 'center',
        fontFamily:'Roboto-Bold',
      },
      login: {
        color: 'blue',
        fontWeight:'400',
        fontSize:16,
        lineHeight:19,
        textAlign:'center',
      },
      svg: {
        position: 'absolute',
        width: 27,
        height: 27,
        left: 235,
        top: 1,
      },

  });

export default styles;